#!/usr/bin/env bash

DOWNLOAD_RET=0
MATHLINGUA_JAR=.bin/mathlingua.jar

# ensure the .bin directory exists so that the download of the
# latest version of MathLingua can continue if .bin/mathlingua.jar
# doesn't exist
mkdir -p .bin

# if the MathLingua jar file doesn't exist, download the latest version
if [ ! -f "${MATHLINGUA_JAR}" ]; then
  echo "Initial run of mlg detected..."
  echo ""
  echo "Downloading the latest version of MathLingua..."

  mkdir -p content

  wget -q -O - https://api.github.com/repos/DominicKramer/mathlingua/releases/latest \
  | grep browser_download_url \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | wget --show-progress -qi - --output-document ${MATHLINGUA_JAR}

  DOWNLOAD_RET=$?
  VERSION=$(./mlg version)

  echo "Downloaded ${VERSION}"
  echo "Subsequent runs of mlg will use this version"
  echo ""
fi

# if there was a failure downloading the latest version of MathLingua
# then describe how to fix the problem
if [ $DOWNLOAD_RET -ne 0 ]; then
  echo "ERROR: Failed downloading the latest version of MathLingua"
  echo ""
  echo "To address this either:"
  echo "1) Ensure wget has been properly installed"
  echo "2) Manually download the latest MathLingua release from"
  echo "   https://github.com/DominicKramer/mathlingua/releases to"
  echo "   $(pwd)/.bin/mathlingua.jar"
  exit 1
fi

# run the MathLingua cli
java -jar ${MATHLINGUA_JAR} $*
